[package]
name = "hw6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.79.0"
rand = "0.8.5"
approx = "0.5.1"
histo = "1.0.0"