all:
	gcc hw0601.c -o hw0601
	gcc hw0602.c simpleeditor.c -o hw0602
	gcc hw0603.c rotation.c -lm -o  hw0603
	gcc hw0604.c projection.c -o hw0604
	gcc hw0605.c sorting.c -o hw0605
clear:
	rm -rf hw0601
	rm -rf hw0602
	rm -rf hw0603
	rm -rf hw0604
	rm -rf hw0605
