all:	
	gcc hw0401.c roman_trans.c -o hw0401
	gcc hw0403.c taylor.c -o hw0403	
	gcc hw0402.c hanoi.c -o hw0402
	gcc hw0404.c eqresis.c -o hw0404
	gcc hw0405.c BullsAndCows.c -o hw0405 
clear:
	rm -rf hw0401
	rm -rf hw0403
	rm -rf hw0402
	rm -rf hw0404
	rm -rf hw0405
