all:
	gcc hw0501.c sorting.c -o hw0501
	gcc hw0502.c determinant.c -o hw0502
	gcc hw0503.c poly.c -o hw0503
	gcc hw0504.c regression.c -o hw0504
clear:
	rm -rf hw0501
	rm -rf hw0502
	rm -rf hw0503
	rm -rf hw0504

